### ISSUE TITLE
Reseting parameters for an unmatched route sets req.Body to nil

### ISSUE THREAD

**Issue by rveen** [DATA-DOG/fastroute#11]
It seems that the call to ps.reset(req) in line 324 of route.go is done with ps.ReadCloser unasigned, that means that req.Body receives a nil in the reset() function. This panics later when calling req.ParseForm()

**Comment by l3pp4rd** [comment]
Hi, interesting, could you show a min example of such use case?

**Comment by l3pp4rd** [comment]
could you check what is different in your case compared to this test added in the commit above?

**Comment by rveen** [comment]
If you add this to your test (at line 197):

    router := fastroute.Chain(fastroute.New("/ff/:id", func(w http.ResponseWriter, r *http.Request) {
    }), fastroute.New("/form/:id", func(w http.ResponseWriter, r *http.Request) {

then it fill panic.

The problem arises when you build a chain, the first route that has a parameter and that route is NOT matched.

**Comment by l3pp4rd** [comment]
thanks, good one. missed the fact that request body is wrapped only when matched.
