### ISSUE TITLE
Native request context

### ISSUE THREAD

**Issue by charbel14** [DATA-DOG/fastroute#12]
Hi,

How do you envision the native http request Context  would work with fastroute?

Consider a case where a middleware needs to set a value into the request context. At the moment this can be done if invoked handler.ServerHTTP( req.WithContext). This seems to defeat the point of returning a handler that fastroute can invoke.

Maybe I am missing something?

```
func aMiddleware(routes ...fastroute.Router) fastroute.Router {
	return fastroute.RouterFunc(func(req *http.Request) http.Handler {
		for _, r := range routes {
			if h := r.Route(req); h != nil {
				req.Header.Set("<set header or better modify context>", "aValue")
				return h 
			}
		}
	})
}
```

**Comment by l3pp4rd** [comment]
Hi, fastroute is built with minimal code to support url parameters and compose the routes, it basically can replace any http router with some customizations.

If you need extreme efficiency for context like parameters. You may copy the code and modify it so that you can add your own parameters instead just having path based parameters carried in request.

It depends on an use case, but using standar go context might be as well a reasonable decision, since it supports the deadline and cancellation.

**Comment by charbel14** [comment]
Thanks for the response.

I was thinking about modifying the parameters to allow for adding a custom one, but then I want to keep the distinction between path params, and middleware injected context values.

If I were to go the native context path:

```
func aMiddleware(routes ...fastroute.Router) fastroute.Router {
	return fastroute.RouterFunc(func(req *http.Request) http.Handler {
		for _, r := range routes {
			if h := r.Route(req); h != nil {
				ctx := req.Context()
				context.WithValue(ctx, "gateway", "myvalue")
				<req = req.WithContext(ctx)... ?>
				return h 
			}
		}
	})
}
```

Also something like:
`fastroute.New("/:id/*", handler)`
Does not seem to work. Is that a defect?

**Comment by l3pp4rd** [comment]
it works as expected, you just need an argument name `/:id/*rest` would match
- `/1/anything` to params `["id": "1", "rest": "/anything"]`
- `/1/path/to/something` to params `["id": "1", "rest": "/path/to/something"]`

**Comment by charbel14** [comment]
Figured after going through the code. Thanks for the quick response. Would be nice to add an example for that case.

**Comment by l3pp4rd** [comment]
There are enough examples for path matching in godoc package description, probably you haven't read it all

**Comment by charbel14** [comment]
Thanks.
Yes. I never looked at these docs. Was going through the readme and code.

I am thinking of adding a logger with latency per request.
