### ISSUE TITLE
maybe static route check not well tested

### ISSUE THREAD

**Issue by davecheney** [DATA-DOG/fastroute#5]
https://github.com/DATA-DOG/fastroute/blob/master/router.go#L263

uses IndexAny(...) == -1, which can be replaced with ContainsAny(...) => bool. However during testing I accidentally used Contains, not ContainsAny and all tests pass. 

This codepath may be under tested.

**Comment by davecheney** [comment]
Ignore me, this was a mistake.

**Comment by l3pp4rd** [comment]
not entirely a mistake, by accident you made that block to skip at all, but static paths can be processed by named parameter matching algorithm without any consequences (apart from using a sync.Pool for empty parameter list). Though, need to think a little more, maybe we can get rid of static path block if performance does not have a big impact.
